#APi Setup
@rootAPI = http://localhost:8001

### Check the server status
GET {{rootAPI}}


### auth post new user
POST {{rootAPI}}/api/v1/auth/register
Content-Type: application/json

{
 "fName": "subekshya",
 "lName": "kharel",
 "email": "i@v.com",
 "phone": "45684569",
 "password": "123"
}

### post to activate user 
POST {{rootAPI}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"684e85d36b8c1f2abb23fc27",
    "t":"f32fb06c-0d55-4afc-aeee-5d2c21aae9af"
}

