#APi Setup
@rootAPI = http://localhost:8000

### Check the server status
GET {{rootAPI}}


### auth post new user
POST {{rootAPI}}/api/v1/auth/register
Content-Type: application/json

{
 "fName": "subekshya",
 "lName": "kharel",
 "email": "i@z.com",
 "phone": "45684569",
 "password": "123"
}

### post to activate user 
POST {{rootAPI}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionId":"684e85d36b8c1f2abb23fc27",
    "t":"f32fb06c-0d55-4afc-aeee-5d2c21aae9af"
}

### Login user  
POST {{rootAPI}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"i@z.com",
    "password":"Subekshya@123"
}

### get user  profile
GET  {{rootAPI}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlAei5jb20iLCJpYXQiOjE3NTAxNzMzNzQsImV4cCI6MTc1MDE3NDI3NH0.m6kGPyK8ym0cpRXXTgA1JiREDJAEs5CxIb9fbtoavig

### get user  profile
GET  {{rootAPI}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlAei5jb20iLCJpYXQiOjE3NTAyNTEyNTIsImV4cCI6MTc1Mjg0MzI1Mn0.iC-dJknIO55crdBEYNwGBf_9Mev9Ljge50Vpngm9kt0

### ggeneraet otp
POST  {{rootAPI}}/api/v1/auth/otp
Content-Type: application/json

{
    "email": "i@z.com"
}

### reset password
POST  {{rootAPI}}/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "i@z.com",
    "password":"321",
    "otp" : 7466
}

#### books

### post books
POST {{rootAPI}}/api/v1/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlAei5jb20iLCJpYXQiOjE3NTA3NzE4MTYsImV4cCI6MTc1MDg1ODIxNn0.qZomVSeSCq3MpIM6omDddg8T0R08mx-gPTUH-FJR-0A

{
  "title": "The Alchemist",
  "year":2008,
  "author": "Paulo Coelho",
  "imgUrl": "https://example.com/images/the-alchemist.jpg",
  "isbn": "9780061122",
  "genre": "Fiction",
  "description": "something"
}

### get all public books
GET  {{rootAPI}}/api/v1/books

### get a single public books
GET  {{rootAPI}}/api/v1/books/public/digital-mirage

### get all books
GET  {{rootAPI}}/api/v1/books/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlAei5jb20iLCJpYXQiOjE3NTA3NzYzMTksImV4cCI6MTc1MDg2MjcxOX0.ivTt1F4o9E16-DbMdK2nKB4Z-rG1uF03TholNAiR4CE

